//
//  ServerUrlInputTests.swift
//  odooTests
//
//  Cross-platform parity table for the login form's server-URL field.
//

import XCTest
@testable import odoo

/// Every row is an input with the outcome Android produces for it
/// (ServerUrlInput.kt at commit 34a6933 + LoginViewModel.goToNextStep ordering:
/// `isInsecure` → HTTPS required, `normalize == nil` → invalid URL, else `displayValue`).
/// Android's expected column was generated by running a Java transcription of the
/// Kotlin code over these exact strings, so both platforms agree on the same inputs.
final class ServerUrlInputTests: XCTestCase {

    private typealias Outcome = ServerUrlInput.Outcome

    private let androidParityTable: [(input: String, expected: Outcome)] = [
        // Scheme handling (already ported in 4616755)
        ("http://insecure.odoo.com", .httpsRequired),
        (" HTTP://demo222-odoo.woowtech.io", .httpsRequired),
        (" http://https://example.invalid", .httpsRequired),
        ("https://secure.odoo.com", .valid("secure.odoo.com")),
        ("my.odoo.com", .valid("my.odoo.com")),
        ("odoo.example.com", .valid("odoo.example.com")),
        ("https://demo222-odoo.woowtech.io ", .valid("demo222-odoo.woowtech.io")),
        ("https://https://demo222-odoo.woowtech.io", .valid("demo222-odoo.woowtech.io")),
        ("  https://https://fixture.invalid  ", .valid("fixture.invalid")),
        (" https://fixture.test  ", .valid("fixture.test")),
        ("　example.invalid　", .valid("example.invalid")), // ideographic spaces are trimmed
        ("  HTTPS://https://HTTPS://example.invalid/erp  ", .valid("example.invalid/erp")),
        ("https://http://example.invalid", .invalid),
        ("https://ftp://example.invalid", .invalid),
        ("ftp://example.invalid", .invalid),
        ("https://https://", .invalid),

        // Host-name character check (HOST_PATTERN)
        ("https;//example.invalid", .invalid), // simulator finding: summary showed https://https;//…
        ("https:/example.invalid", .invalid),
        ("demo222 odoo.woowtech.io", .invalid),
        ("bad host", .invalid),
        ("odoo_prod.example.invalid", .invalid), // underscore
        ("ｏｄｏｏ.example.invalid", .invalid), // full-width letters
        ("example.invalid：8069", .invalid), // full-width colon
        ("example.invalid:８０６９", .invalid), // full-width digits in port
        ("例子.example.invalid", .invalid), // non-ASCII (IDN is not accepted)
        ("-example.invalid", .invalid),
        ("example.invalid-", .invalid),
        (".example.invalid", .invalid),
        ("example.invalid.", .invalid),
        ("user@example.invalid", .invalid),
        ("[::1]", .invalid),
        ("example.invalid:8069", .valid("example.invalid:8069")),
        ("example.invalid:123456", .invalid),
        ("example.invalid:", .invalid),
        ("example.invalid:abc", .invalid),
        ("192.168.0.10:8069", .valid("192.168.0.10:8069")),
        ("localhost", .valid("localhost")),
        ("a", .valid("a")),
        // Android quirk kept for parity: `https//x` has host `https` and path `x`.
        ("https//example.invalid", .valid("https//example.invalid")),

        // Browser-copied Odoo paths, query and fragment are dropped; other paths kept
        ("HTTPS://demo222-odoo.woowtech.io/web#action=menu", .valid("demo222-odoo.woowtech.io")),
        ("https://example.invalid/web", .valid("example.invalid")),
        ("example.invalid/web/login?db=x", .valid("example.invalid")),
        ("example.invalid/odoo", .valid("example.invalid")),
        ("example.invalid/odoo/action-123", .valid("example.invalid")),
        ("example.invalid/website", .valid("example.invalid")), // Android prefix match on "web"
        ("example.invalid?db=x", .valid("example.invalid")),
        ("example.invalid#frag", .valid("example.invalid")),
        ("example.invalid/", .valid("example.invalid")),
        ("example.invalid/erp/", .valid("example.invalid/erp")),
        ("example.invalid/erp?x=1", .valid("example.invalid/erp")),
    ]

    func test_classify_givenAndroidParityTable_matchesAndroidOutcome() {
        for row in androidParityTable {
            XCTAssertEqual(ServerUrlInput.classify(row.input), row.expected,
                           "input [\(row.input)]")
        }
    }
}

// MARK: - Login form wiring

@MainActor
final class ServerUrlInputLoginFormTests: XCTestCase {

    private func makeServerStepViewModel(serverUrl: String) -> LoginViewModel {
        let vm = LoginViewModel(addingAccount: true,
                                repository: MockAccountRepository(),
                                secureStorage: MockSecureStorage())
        vm.serverUrl = serverUrl
        vm.database = "mydb"
        return vm
    }

    /// Simulator finding: `https;//example.invalid` was accepted and the credentials
    /// summary showed `https://https;//example.invalid`.
    func test_goToNextStep_givenSemicolonInsteadOfColonInScheme_showsInvalidUrlError() {
        let vm = makeServerStepViewModel(serverUrl: "https;//example.invalid")
        vm.goToNextStep()
        XCTAssertEqual(vm.error, String(localized: "error_invalid_server_url"))
        XCTAssertEqual(vm.step, .serverInfo)
        XCTAssertEqual(vm.serverUrl, "https;//example.invalid", "rejected input stays as typed")
    }

    func test_goToNextStep_givenUnderscoreHost_showsInvalidUrlError() {
        let vm = makeServerStepViewModel(serverUrl: "odoo_prod.example.invalid")
        vm.goToNextStep()
        XCTAssertEqual(vm.error, String(localized: "error_invalid_server_url"))
        XCTAssertEqual(vm.step, .serverInfo)
    }

    func test_goToNextStep_givenPastedBrowserUrl_summaryShowsServerOnly() {
        let vm = makeServerStepViewModel(serverUrl: "HTTPS://demo222-odoo.woowtech.io/odoo/action-123?debug=1#x")
        vm.goToNextStep()
        XCTAssertNil(vm.error)
        XCTAssertEqual(vm.step, .credentials)
        XCTAssertEqual(vm.serverUrl, "demo222-odoo.woowtech.io")
        XCTAssertEqual(vm.displayUrl, "https://demo222-odoo.woowtech.io")
    }
}

// MARK: - Fixed "https://" label (Android W2-4 U4)

/// The field's fixed `https://` label made a typed `http://host` read as `https://http://host`.
/// The label is hidden once the text carries its own scheme; validation is unchanged.
final class ServerUrlSchemePrefixTests: XCTestCase {

    func test_showsFixedSchemePrefix_givenBareHostOrEmpty_returnsTrue() {
        for raw in ["", "   ", "h", "http", "https", "http:", "http:/", "example.invalid",
                    "example.invalid:8069", "example.invalid/erp/a://b", "https;//example.invalid",
                    "odoo_prod.example.invalid", "1http://x", "://example.invalid"] {
            XCTAssertTrue(ServerUrlInput.showsFixedSchemePrefix(for: raw), "label hidden for '\(raw)'")
        }
    }

    func test_showsFixedSchemePrefix_givenTextWithScheme_returnsFalse() {
        for raw in ["http://", "http://insecure.example.invalid", " HTTP://example.invalid",
                    "https://example.invalid", "HTTPS://https://example.invalid", "ftp://example.invalid",
                    "\u{3000}http://example.invalid", "git+ssh://example.invalid"] {
            XCTAssertFalse(ServerUrlInput.showsFixedSchemePrefix(for: raw), "label shown for '\(raw)'")
        }
    }

    /// Display-only: the inputs whose label is hidden are still classified exactly as before.
    func test_showsFixedSchemePrefix_givenHiddenLabel_leavesClassificationUnchanged() {
        XCTAssertEqual(ServerUrlInput.classify("http://insecure.example.invalid"), .httpsRequired)
        XCTAssertEqual(ServerUrlInput.classify("https://example.invalid"), .valid("example.invalid"))
        XCTAssertEqual(ServerUrlInput.classify("ftp://example.invalid"), .invalid)
    }
}

// MARK: - Accepted path containing "://" reaches every consumer with one https

/// Review finding (iOS P2): `classify` accepts `https://example.invalid/erp/a://b` and
/// returns the scheme-less `example.invalid/erp/a://b`, but `ensureHTTPS` used to treat
/// the `://` inside the path as an existing scheme and return the bare value — the
/// summary lost `https://` and `OdooAPIClient` rejected the login as "HTTPS required".
/// One fixture, walked through classify → ViewModel summary → the URL the real
/// repository + API client actually request.
@MainActor
final class ServerUrlPathSchemeChainTests: XCTestCase {

    private static let fixture = "https://example.invalid/erp/a://b"

    /// Records the one authenticate POST and answers HTTP 500 so no account is created.
    private final class AuthRecordingURLProtocol: URLProtocol {
        static var recordedURLs: [URL] = []

        override class func canInit(with request: URLRequest) -> Bool { true }
        override class func canonicalRequest(for request: URLRequest) -> URLRequest { request }

        override func startLoading() {
            if let url = request.url { Self.recordedURLs.append(url) }
            let response = HTTPURLResponse(url: request.url ?? URL(string: "https://localhost")!,
                                           statusCode: 500, httpVersion: nil, headerFields: nil)!
            client?.urlProtocol(self, didReceive: response, cacheStoragePolicy: .notAllowed)
            client?.urlProtocol(self, didLoad: Data())
            client?.urlProtocolDidFinishLoading(self)
        }

        override func stopLoading() {}
    }

    override func setUp() {
        super.setUp()
        AuthRecordingURLProtocol.recordedURLs = []
    }

    override func tearDown() {
        AuthRecordingURLProtocol.recordedURLs = []
        super.tearDown()
    }

    func test_classify_givenColonSlashInPath_keepsPathWithoutScheme() {
        XCTAssertEqual(ServerUrlInput.classify(Self.fixture), .valid("example.invalid/erp/a://b"))
    }

    func test_loginFlow_givenColonSlashInPath_summaryAndAuthenticateUseSingleHttpsWithPath() async {
        let config = URLSessionConfiguration.ephemeral
        config.protocolClasses = [AuthRecordingURLProtocol.self]
        let repository = AccountRepository(
            persistence: PersistenceController(inMemory: true),
            apiClient: OdooAPIClient(session: URLSession(configuration: config)),
            brand: .woowtech
        )
        let vm = LoginViewModel(addingAccount: true, repository: repository,
                                secureStorage: MockSecureStorage())
        vm.serverUrl = Self.fixture
        vm.database = "mydb"

        vm.goToNextStep()

        XCTAssertNil(vm.error)
        XCTAssertEqual(vm.step, .credentials)
        XCTAssertEqual(vm.serverUrl, "example.invalid/erp/a://b")
        XCTAssertEqual(vm.displayUrl, "https://example.invalid/erp/a://b")
        XCTAssertEqual(vm.displayUrl.components(separatedBy: "https://").count - 1, 1,
                       "summary shows exactly one https://")

        vm.username = "admin"
        vm.password = "fixture-password"
        vm.login(onSuccess: {})
        for _ in 0..<500 where vm.isLoading {
            try? await Task.sleep(nanoseconds: 10_000_000)
        }

        XCTAssertFalse(vm.isLoading, "login did not finish")
        XCTAssertNotEqual(vm.error, String(localized: "error_https_required"),
                          "API client must not reject the accepted URL as non-HTTPS")
        XCTAssertEqual(AuthRecordingURLProtocol.recordedURLs.map(\.absoluteString),
                       ["https://example.invalid/erp/a://b/web/session/authenticate"],
                       "authenticate serverUrl is the full https URL with the path kept")
    }
}
