//
//  ServerUrlInputTests.swift
//  odooTests
//
//  Cross-platform parity table for the login form's server-URL field.
//

import XCTest
@testable import odoo

/// Every row is an input with the outcome Android produces for it
/// (ServerUrlInput.kt at commit 34a6933 + LoginViewModel.goToNextStep ordering:
/// `isInsecure` → HTTPS required, `normalize == nil` → invalid URL, else `displayValue`).
/// Android's expected column was generated by running a Java transcription of the
/// Kotlin code over these exact strings, so both platforms agree on the same inputs.
final class ServerUrlInputTests: XCTestCase {

    private typealias Outcome = ServerUrlInput.Outcome

    private let androidParityTable: [(input: String, expected: Outcome)] = [
        // Scheme handling (already ported in 4616755)
        ("http://insecure.odoo.com", .httpsRequired),
        (" HTTP://demo222-odoo.woowtech.io", .httpsRequired),
        (" http://https://example.invalid", .httpsRequired),
        ("https://secure.odoo.com", .valid("secure.odoo.com")),
        ("my.odoo.com", .valid("my.odoo.com")),
        ("odoo.example.com", .valid("odoo.example.com")),
        ("https://demo222-odoo.woowtech.io ", .valid("demo222-odoo.woowtech.io")),
        ("https://https://demo222-odoo.woowtech.io", .valid("demo222-odoo.woowtech.io")),
        ("  https://https://fixture.invalid  ", .valid("fixture.invalid")),
        (" https://fixture.test  ", .valid("fixture.test")),
        ("　example.invalid　", .valid("example.invalid")), // ideographic spaces are trimmed
        ("  HTTPS://https://HTTPS://example.invalid/erp  ", .valid("example.invalid/erp")),
        ("https://http://example.invalid", .invalid),
        ("https://ftp://example.invalid", .invalid),
        ("ftp://example.invalid", .invalid),
        ("https://https://", .invalid),

        // Host-name character check (HOST_PATTERN)
        ("https;//example.invalid", .invalid), // simulator finding: summary showed https://https;//…
        ("https:/example.invalid", .invalid),
        ("demo222 odoo.woowtech.io", .invalid),
        ("bad host", .invalid),
        ("odoo_prod.example.invalid", .invalid), // underscore
        ("ｏｄｏｏ.example.invalid", .invalid), // full-width letters
        ("example.invalid：8069", .invalid), // full-width colon
        ("example.invalid:８０６９", .invalid), // full-width digits in port
        ("例子.example.invalid", .invalid), // non-ASCII (IDN is not accepted)
        ("-example.invalid", .invalid),
        ("example.invalid-", .invalid),
        (".example.invalid", .invalid),
        ("example.invalid.", .invalid),
        ("user@example.invalid", .invalid),
        ("[::1]", .invalid),
        ("example.invalid:8069", .valid("example.invalid:8069")),
        ("example.invalid:123456", .invalid),
        ("example.invalid:", .invalid),
        ("example.invalid:abc", .invalid),
        ("192.168.0.10:8069", .valid("192.168.0.10:8069")),
        ("localhost", .valid("localhost")),
        ("a", .valid("a")),
        // Android quirk kept for parity: `https//x` has host `https` and path `x`.
        ("https//example.invalid", .valid("https//example.invalid")),

        // Browser-copied Odoo paths, query and fragment are dropped; other paths kept
        ("HTTPS://demo222-odoo.woowtech.io/web#action=menu", .valid("demo222-odoo.woowtech.io")),
        ("https://example.invalid/web", .valid("example.invalid")),
        ("example.invalid/web/login?db=x", .valid("example.invalid")),
        ("example.invalid/odoo", .valid("example.invalid")),
        ("example.invalid/odoo/action-123", .valid("example.invalid")),
        ("example.invalid/website", .valid("example.invalid")), // Android prefix match on "web"
        ("example.invalid?db=x", .valid("example.invalid")),
        ("example.invalid#frag", .valid("example.invalid")),
        ("example.invalid/", .valid("example.invalid")),
        ("example.invalid/erp/", .valid("example.invalid/erp")),
        ("example.invalid/erp?x=1", .valid("example.invalid/erp")),
    ]

    func test_classify_givenAndroidParityTable_matchesAndroidOutcome() {
        for row in androidParityTable {
            XCTAssertEqual(ServerUrlInput.classify(row.input), row.expected,
                           "input [\(row.input)]")
        }
    }
}

// MARK: - Login form wiring

@MainActor
final class ServerUrlInputLoginFormTests: XCTestCase {

    private func makeServerStepViewModel(serverUrl: String) -> LoginViewModel {
        let vm = LoginViewModel(addingAccount: true,
                                repository: MockAccountRepository(),
                                secureStorage: MockSecureStorage())
        vm.serverUrl = serverUrl
        vm.database = "mydb"
        return vm
    }

    /// Simulator finding: `https;//example.invalid` was accepted and the credentials
    /// summary showed `https://https;//example.invalid`.
    func test_goToNextStep_givenSemicolonInsteadOfColonInScheme_showsInvalidUrlError() {
        let vm = makeServerStepViewModel(serverUrl: "https;//example.invalid")
        vm.goToNextStep()
        XCTAssertEqual(vm.error, String(localized: "error_invalid_server_url"))
        XCTAssertEqual(vm.step, .serverInfo)
        XCTAssertEqual(vm.serverUrl, "https;//example.invalid", "rejected input stays as typed")
    }

    func test_goToNextStep_givenUnderscoreHost_showsInvalidUrlError() {
        let vm = makeServerStepViewModel(serverUrl: "odoo_prod.example.invalid")
        vm.goToNextStep()
        XCTAssertEqual(vm.error, String(localized: "error_invalid_server_url"))
        XCTAssertEqual(vm.step, .serverInfo)
    }

    func test_goToNextStep_givenPastedBrowserUrl_summaryShowsServerOnly() {
        let vm = makeServerStepViewModel(serverUrl: "HTTPS://demo222-odoo.woowtech.io/odoo/action-123?debug=1#x")
        vm.goToNextStep()
        XCTAssertNil(vm.error)
        XCTAssertEqual(vm.step, .credentials)
        XCTAssertEqual(vm.serverUrl, "demo222-odoo.woowtech.io")
        XCTAssertEqual(vm.displayUrl, "https://demo222-odoo.woowtech.io")
    }
}
